AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template to define Cognito and associated resources for development 
  
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter dev for development and prod for production
  
Mappings: 
  CognitoCallbackUrls:
    dev:
      values: 'http://localhost:4200/login/callback,https://dev.hvgn.net/login/callback'
    prod:
      values: 'https://hvgn.net/login/callback'
  CognitoLogoutUrls:
    dev:
      values: 'http://localhost:4200,https://dev.hvgn.net'
    prod:
      values: 'https://hvgn.net'
  CognitoCustomDomain:
    dev:
      url: hvgn-dev-auth
    prod: 
      url: hvgn-auth

Resources:
  AssignGroupCognitoTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: assign-group/
      Handler: app.handler
      Runtime: nodejs14.x
      Role: !GetAtt AssignGroupCognitoTriggerExecutionRole.Arn
      Events:
        CognitoPostConfirmationEvent:
          Type: Cognito
          Properties:
            Trigger: 
              - PostConfirmation
            UserPool: !Ref CognitoUserPool

  AssignGroupCognitoTriggerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Join
            - ''
            - - 'assign-group-cognito-trigger-'
              - !Ref Environment
              - '-policy'
          PolicyDocument:
            Statement:
              - Sid: CognitoAssignUserToGroupLogs
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource: '*'
              - Sid: CognitoAssignUserToGroupLogEvents
                Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: '*'
              - Sid: CognitoAssignUserToGroupCommand
                Effect: Allow
                Action:
                  - cognito-idp:AdminAddUserToGroup
                Resource: !Join
                  - ''
                  - - 'arn:aws:cognito-idp:'
                    - !Ref "AWS::Region"
                    - ':'
                    - !Ref "AWS::AccountId"
                    - ':userpool/*'    
 
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: 'Your email had been verified {####}.'
      EmailVerificationSubject: 'Email verification'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      UsernameAttributes:
        - email
      UserPoolName: !Join
        - '-'
        - - 'hvgn'
          - !Ref Environment
          - 'user-pool'
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: 'Your verification code is {####}.' 
        EmailSubject: Your verification code

  CognitoUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: 'General group for HVGN'
      GroupName: hvgn-view
      Precedence: 5
      RoleArn: !GetAtt HvgnBackendLambdaExecutionRole.Arn
      UserPoolId: !Ref CognitoUserPool

  GoogleFederatedIdentity:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      AttributeMapping:
        email: "email"
      ProviderDetails:
        client_id: "{{resolve:secretsmanager:HvgnCognitoGoogleIdentityProvider:SecretString:HvgnCognitoGoogleClientId}}"
        client_secret: "{{resolve:secretsmanager:HvgnCognitoGoogleIdentityProvider:SecretString:HvgnCognitoGoogleClientSecret}}"
        authorize_scopes: "profile email openid"
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref CognitoUserPool

  CognitoClientApplication:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: 
      - GoogleFederatedIdentity
      - HvgnResourceServer
    Properties:
      AccessTokenValidity: 30
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
        - 'api.hvgn.net/hvgn'
      CallbackURLs: !Split [",", !FindInMap [ CognitoCallbackUrls, !Ref Environment, values] ]
      ClientName: !Join
        - ''
        - - 'hvgn-cognito-client-'
          - !Ref Environment
      EnableTokenRevocation: true
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      IdTokenValidity: 30
      LogoutURLs: !Split [",", !FindInMap [ CognitoLogoutUrls, !Ref Environment, values] ]
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 60
      SupportedIdentityProviders:
        - COGNITO
        - Google
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: minutes
      UserPoolId: !Ref CognitoUserPool

# AWS does not provide a way in CloudFormtaion to link a Route53 alias record
# to a Cognito User Pool Domain.  YOu must use a custom resource.  Specifically,
# there is no 'AliasTarget' attribute for type 'AWS::Cognito::UserPoolDomain'.
# See https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/241
# See https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/356

# This template will use the built-in domain customization.      

  CognitoUserPoolCustomDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
#      CustomDomainConfig:
#        CertificateArn: "{{resolve:secretsmanager:HvgnDomainCertificate:SecretString:arn}}"
      Domain: !FindInMap [ CognitoCustomDomain, !Ref Environment, url]
      UserPoolId: !Ref CognitoUserPool

#  CogntioCustomDomainAliasRecord:
#    Type: AWS::Route53::RecordSet
#    Properties:
#      AliasTarget: !GetAtt CognitoUserPoolCustomDomain.AliasTarget
#      HostedZoneName: 'hvgn.net.'
#      Name: !FindInMap [ CognitoCustomDomain, !Ref Environment, url]
#      Type: A

  HvgnResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: api.hvgn.net
      Name: hvgn
      Scopes:
        - ScopeDescription: Allow access to HVGN services
          ScopeName: hvgn
      UserPoolId: !Ref CognitoUserPool

  HvgnBackendLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join 
        - '-'
        - - 'hvgn-backend-lambda'
          - !Ref Environment
          - 'execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Join
            - '-'
            - - 'hvgn-backend-lambda'
              - !Ref Environment
              - 'execution-policy'            
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource: !Join
                  - ''
                  - - 'arn:aws:logs:'
                    - !Ref "AWS::Region"
                    - ':'
                    - !Ref "AWS::AccountId"
                    - ':log-group:/aws/lambda/hvgn-backend-'
                    - !Ref Environment
                    - '*:*'
              - Effect: Allow
                Action: 
                  - logs:PutLogEvents
                Resource: !Join
                  - ''
                  - - 'arn:aws:logs:'
                    - !Ref "AWS::Region"
                    - ':'
                    - !Ref "AWS::AccountId"
                    - ':log-group:/aws/lambda/hvgn-backend-'
                    - !Ref Environment
                    - '*:*:*'                  
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource: !Join
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref "AWS::Region"
                    - ':'
                    - !Ref "AWS::AccountId"
                    - ':table/hvgn-'
                    - !Ref Environment     
      
Outputs:
  CognitoUserPoolArn:
    Description: The ARN of the user pool
    Value: !GetAtt CognitoUserPool.Arn
    Export:
      Name: !Join
        - '-'
        - - 'HvgnUserPoolArn'
          - !Ref Environment
